name: Dependabot Auto Test, Bump & Publish

permissions:
  contents: read # to be able to publish a GitHub release
#  issues: write # to be able to comment on released issues
#  pull-requests: write # to be able to comment on released pull requests
#  id-token: write # to enable use of OIDC for npm provenance

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - "*.x"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
        env:
          KV_SMOKE: 1
          KV_STRESS: 1
          DEBUG: 1
      - run: corepack enable && corepack prepare yarn@4.9.1 --activate
      - run: which yarn node git
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn build
      - run: yarn vitest --coverage --reporter=verbose
      - run: ./scripts/smoke-local.sh        

  coveralls-runner:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: corepack enable && corepack prepare yarn@4.9.1 --activate
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn vitest --coverage --reporter=verbose
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info

  # automatically bump and publish on fix: feat: BREAKING CHANGE:
  test-bump-and-publish-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: corepack enable && corepack prepare yarn@4.9.1 --activate
      - run: yarn install --immutable
      - name: Set up git authentication
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOPE: ${{secrets.scope}}
          NODE_AUTH_TOKEN: ${{ secrets.VS_NPM_TOKEN}}
          NPM_TOKEN: ${{ secrets.VS_NPM_TOKEN}}
